### PR TITLE
bump to alpine 3.6 and glibc 2.28-r0

### PR DESCRIPTION
**Pull request by Francesco149**
I noticed the adb version in the image was old enough to be incompatible with adb 1.0.40 clients so I decided to rebuild it and it wasn't building due to the dead sgerrand pubkey url

I went ahead and updated everything so it builds again

oh yeah, and since docker tar's the entire working directory i added a .dockerignore to exclude files it doesnt need at build time

### CODE REVIEW

**Comment by sorccu** [comment]
Great patch. Wish docker hub sent an email when builds start failing.

**Comment by gounthar** [comment]
I never got why this particular version of glibc was necessary. Could you please shortly elaborate?
Thanks a lot.

**Comment by Francesco149** [comment]
I'm not actually sure the glibc bump was necessary

basically what happened is the old pubkey at https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/sgerrand.rsa.pub 404's and the one at https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub is not necessarily the same that was used to sign glibc-2.23-r3{,-bin}.apk

you can try just using the new pubkey and the old apk's and see if it still builds, I just thought I'd go ahead and match the latest packages on sgerrand's repo while I was at it

**Comment by Francesco149** [comment]
according to sgerrand's readme, ```Any previous reference to https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub should be updated with immediate effect to https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub.```

so in theory it should work with 2.23-r3 as well if you prefer using that

**Pull request merged**
